import axios from "axios";

axios.defaults.withCredentials = true;
axios.defaults.baseURL = process.env.VUE_APP_API_URL;

export default {
  namespaced: true,
  state: {
    pet: {
      petId: 0,
      pet_avatar: "",
      pet_name: "",
      pet_sterilized: false,
      pet_birth_date: "",
      pet_gender: null,
      pet_chip_number: "",
      pet_general_instructions: "",
      pet_breed_id: 0,
      pet_size_id: 0,
      pet_fur_id: 0,
      pet_food_id: 0,
    },
    vet_information: {
      veterinarian_name: null,
      veterinarian_phone: null,
      veterinarian_ubication: null,
      rabies_vaccine: null,
      pentavalent_vaccine: null,
      cough_vaccine: null,
      vaccination_card: null,
      normal_locomotion: null,
      head: null,
      neck: null,
      front_legs: null,
      hind_legs: null,
      back: null,
      belly: null,
    },
    pet_behavior: {
      socialization: 0,
      energy: 0,
      bark: 0,
      anxiety: 0,
      aggressiveness: 0,
      general_temperament: 0,
      ride: false,
    },
    // Default format
    default_pet: {
      petId: 0,
      pet_avatar: "",
      pet_name: "",
      pet_sterilized: false,
      pet_birth_date: "",
      pet_gender: null,
      pet_chip_number: "",
      pet_general_instructions: "",
      pet_breed_id: 0,
      pet_size_id: 0,
      pet_fur_id: 0,
      pet_food_id: 0,
    },
    default_vet_information: {
      veterinarian_name: null,
      veterinarian_phone: null,
      veterinarian_ubication: null,
      rabies_vaccine: null,
      pentavalent_vaccine: null,
      cough_vaccine: null,
      vaccination_card: null,
      normal_locomotion: null,
      head: null,
      neck: null,
      front_legs: null,
      hind_legs: null,
      back: null,
      belly: null,
    },
    default_pet_behavior: {
      socialization: 0,
      energy: 0,
      bark: 0,
      anxiety: 0,
      aggressiveness: 0,
      general_temperament: 0,
      ride: false,
    },
  },
  mutations: {},
  actions: {},
  getters: {},
};
